apiVersion: apps/v1
kind: Deployment
metadata:
  name: daabuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daabuggy
  template:
    metadata:
      labels:
        app: daabuggy
    spec:
      containers:
      - name: daabuggy
        image: 182399689628.dkr.ecr.us-east-1.amazonaws.com/daa
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: daabuggy
    k8s-app: daabuggy
  name: daabuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: daabuggy
